export * from './dashboard';
export * from './auth';
export * from './login';
export * from './not-found';
export * from './register';
export * from './unauthorized';

export { ForgotPasswordPage } from './forgot-password';
export { ResendVerificationPage } from './resend-verification';
export { ResetPasswordPage } from './reset-password';
export { VerifyEmailPage } from './verify-email';
export { AdminDashboardPage } from './admin-dashboard-page';
export { AdminPointsPage } from './admin-points-page';
export { AdminUsersPage } from './admin-users-page';
export { AnalyticsPage } from './analytics-page';
export { BookmarksPage } from './bookmarks-page';
export { CategoriesPage } from './categories-page';
export { CategoryDetailPage } from './category-detail-page';
export { DocumentDetailPage } from './document-detail-page';
export { DocumentsPage } from './documents-page';
export { MyDocumentsPage } from './my-documents-page';
export { NotificationsPage } from './notifications-page';
export { ProfilePage } from './profile-page';
export { SettingsPage } from './settings-page';
export { SystemSettingsPage } from './system-settings-page';
export { TopRatedPage } from './top-rated-page';
export { TrendingPage } from './trending-page';
export { UploadPage } from './upload-page';
